### ISSUE TITLE
Suggestions or potential ideas - Junit test runner integration

### ISSUE THREAD

**Issue by yveszoundi** [yyoncho/dap-mode#1]
I noticed that you've been experimenting with `Eclipse che` per look at the source code.
Based on the work that you've got so far and the `lsp-java` code, I've integrated junit testing with LSP in my current workflow (tested only on simple projects, not perfect but I'm happy so far):
- I'm leveraging `semantic` to get the current package or method name via `semantic-brute-find-tag-by-class` and `semantic-brute-find-tag-by-position` per code below.
- I'm using a custom variable `junit-platform-jar-file` serving the same purposes as what you've got in `dap-java-test-runner`.
- Most of the time, I either want to run all the tests (Maven or gradle) or specific ones (if possible without invoking a build tool). In my case, having a tests explorer is not a critical feature (`vscode-java-test`).

I'm posting what I use so far, in case it might help you with your design and overall ideas. 
Thanks for your efforts and good work on Emacs packages, I'm experimenting once in a while with `dap-mode` and it looks very promising.

## Try running the test under the cursor

This tries running the enclosing test closer to the point, it falls back to running the entire test class.

```emacs-lisp
(defun ers/lsp-run-test-method ()
  (interactive)
  (let* ((cls-name     (file-name-sans-extension (file-name-nondirectory buffer-file-name)))
         (pkg-name     (caar (semantic-brute-find-tag-by-class 'package (current-buffer))))
         (fqcn         (concat pkg-name "." cls-name))
         (method-name  (caar
                        (cl-remove-if-not
                         (lambda (m)
                           (and (consp (last m))
                                (overlayp (first (last m)))
                                (>= (point) (overlay-start (first (last m))))
                                (<= (point) (overlay-end (first (last m))))))
                         (first
                          (cl-remove-if-not
                           (lambda (elt)
                             (and (consp elt)
                                  (> (length elt) 1)))
                           (first
                            (cl-remove-if-not
                             'consp
                             (semantic-brute-find-tag-by-position (point) (current-buffer))))))))))
    (if method-name
        (compile
         (concat "java -jar "
                 junit-platform-jar-file
                 " --class-path "
                 (mapconcat 'identity (cadr (lsp-send-execute-command "vscode.java.resolveClasspath" (list fqcn nil ))) ":")
                 " -f "
                 (buffer-file-name)
                 " -m "
                 (concat fqcn "#" method-name)
                 " --details verbose")
         t)
      (ers/lsp-test-run-test-class))))
```
## Run a test class

```emacs-lisp
(defun ers/lsp-run-test-class ()
  (interactive)
  (let* ((cls-name (file-name-sans-extension (file-name-nondirectory buffer-file-name)))
         (pkg-name (caar (semantic-brute-find-tag-by-class 'package (current-buffer))))
         (fqcn     (concat pkg-name "." cls-name)))
    (compile
     (concat "java -jar " junit-platform-jar-file
             " --class-path "
             (mapconcat 'identity (cadr (lsp-send-execute-command "vscode.java.resolveClasspath" (list fqcn nil ))) ":")
             " -f " (buffer-file-name)
             " --include-package " pkg-name " -c " fqcn " --details verbose")
     t)))
```

**Comment by yveszoundi** [comment]
Thanks for the details, totally agreed for your point about non AST solutions.

Would it be possible to extract the `test method name lookup` though?
- Useful for people that can't install `Eclipse che` (mainly corporate computer software installation restrictions, win* PC without hyper-v, etc.): I'm sometimes forced to use specific versions of Windows with limited privileges because clients request it (can't always use Linux or OSX or an "acceptable windows setup").
- In my case, it means that I could still opt-in for a conscious unreliable solution (test method names), but I'd still be able to use all that `dap-mode` has to offer without `Eclipse che` ->  override the `defun`

I'm talking more specifically about the following snippet in `dap-java`:
```emacs-lisp
(->> (list :cursorOffset (point)
                             :sourceUri (lsp--path-to-uri (buffer-file-name)))
                       (lsp-send-execute-command "che.jdt.ls.extension.findTestByCursor")
first)
```
I suppose that "findTestByCursor" is possibly provided by a custom Che extension. If that's the case and it can also be available for eclipse jdt ls, that would be great.

**Comment by yyoncho** [comment]
Sure, I am not happy with the current design test execution, once I fix that I hope the functionallity you are asking for will be present:

It will look like something like 

``` elisp
(defun my/run-test ()
  (dap-debug (list :type "attach"
                            ;; optional program to start
                            :program {-plug-whatever-you-want-}
                            .... )))
```

Just for your information(I am about to update the readme) Eclipse Che JDT is avaiable through: 
http://download.eclipse.org/che/che-ls-jdt/snapshots/

Here are some of the methods provided by the extension. Exposing them in `lsp-java` is in my TODO list. 

https://github.com/eclipse/che-ls-jdt/blob/master/org-eclipse-che-jdt-ls-extension/jdt.ls.extension.core/src/main/java/org/eclipse/che/jdt/ls/extension/core/internal/CheDelegateCommandHandler.java

**Comment by yveszoundi** [comment]
I just switched to `Eclipse che seamlessly` thanks to the link that you provided. The online Che docs seem to emphasize on docker, k8s, etc.

I'm finding the `step-in/out` behavior a bit confusing, as I didn't see a `step-over` command. Would `step-over` be easy to implement or is the functionality elsewhere (i.e just use `continue` for now)?

For a not fully polished/finished product, `dap-mode` already does pretty much what I need for occasional debugging, in addition to running main classes . `dap-eval` is extremely useful. 
- I'm hoping for visual indicators/overlays in the code when the current thread is suspended in the future: maybe it's there already, I'm using emacs mostly within a tmux session in the terminal. I navigate between the locals/session windows for now and expand to get details.
- Anything else that I'd comment on is likely covered by your todos, including my previous point..

Well done sir! :+1:

**Comment by yyoncho** [comment]
`step-over` = `dap-next`

There are the following faces `dap-ui-pending-breakpoint-face`, `dap-ui-verified-breakpoint-face`, and `dap-ui-marker-face` which you can customize to get visual indications for breakpoints/cursor position line. By default there are only fringe indicators which is not visible in the TUI.

**Comment by yveszoundi** [comment]
Thanks, things work great for my terminal workflow, closing. Maybe `dap-next` could be renamed or aliased to `step-over` for consistency and metaphors employed in other dev environments?

I like the fact that you didn't force key bindings to the user. For many packages, it's a complicated affair, especially when the prefix key is not customizable (in comparison to `projectile` for example).

**Comment by yyoncho** [comment]
I am naming the methods after the `Debug Adapter Protocol` methods - https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L557
