### ISSUE TITLE
got follow error msgs when after eval 'dap-breakpoint-add 

### ISSUE THREAD

**Issue by rdzhuang** [yyoncho/dap-mode#13]
```
Debugger entered--Lisp error: (cl-assertion-failed ((lsp--workspace-p lsp--cur-workspace) nil))
  cl--assertion-failed((lsp--workspace-p lsp--cur-workspace))
  dap-breakpoint-add()
  funcall-interactively(dap-breakpoint-add)
  #<subr call-interactively>(dap-breakpoint-add record nil)
  apply(#<subr call-interactively> dap-breakpoint-add (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> dap-breakpoint-add record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (dap-breakpoint-add record nil))
  call-interactively(dap-breakpoint-add record nil)
  command-execute(dap-breakpoint-add record)
  #f(compiled-function (cmd) #<bytecode 0x4414d6f1>)("dap-breakpoint-add")

```

**Comment by yyoncho** [comment]
Can you make sure you have added the breakpoint in file which is managed by `lsp-mode`. E.g . if you were using `lsp-java` you should have called `lsp-java-enable` before adding the breakpoint.

**Comment by rdzhuang** [comment]
@yyoncho 
I am sure I enabled the mode.

![image](https://user-images.githubusercontent.com/18410869/47707528-06e1be80-dc67-11e8-83a4-b450ec42df9e.png)

**Comment by yyoncho** [comment]
For some reason `lsp--cur-workspace` is nil for that file. I guess the other features are not working too(e. g. goto definition). Can you provide the content of `\*Messages\*` buffer + link to your `lsp-mode` related configuration? This could happen if you have called `lsp-mode` instead of `lsp-java-enable`.

**Comment by rdzhuang** [comment]
@yyoncho 
For example in local config: 

`
(require 'lsp-java)
(add-hook 'java-mode-hook #'lsp-java-enable)
(setq company-lsp-cache-candidates t
      company-lsp-async t)

(dap-mode 1)
(dap-ui-mode 1)
(require 'dap-java)
(require 'lsp-java-treemacs)
`
And in the `*Messages*` buffer, just got a message: `cl--assertion-failed: Assertion failed: (lsp--workspace-p lsp--cur-workspace)`

**Comment by rdzhuang** [comment]
@yyoncho  Thanks so much!  It works for me after I reinstall dap-mode.

**Comment by yyoncho** [comment]
You welcome. In general, you may try using `lsp-ui` as well.
