### ISSUE TITLE
Setting constant symbol

### ISSUE THREAD

**Issue by jsalzbergedu** [yyoncho/dap-mode#14]
Hey, I've had a little issue with dap-mode: any attempt to run/debug a test or class simply does not work/

With debug-on-error set to t, I can see that the stacktrace is:

```
Debugger entered--Lisp error: (setting-constant :skip-debug-session)
  dap-start-debugging((:type "java" :request "attach" :hostName "localhost" :port 33000 :wait-for-port t 
...
```
I've narrowed down the error to the -let* binding in the method dap-start-debugging. My version of dash is `2.14.1`.

Thank you!

**Comment by yyoncho** [comment]
I am using the new "smarter" destructuring introduced with the following CL: https://github.com/magnars/dash.el/commit/e52909f0989bd562ce3e6cc84bc7c64ccc2f6fd8 
Upgrading to latest melpa release should fix the issue.

**Comment by yyoncho** [comment]
> Upgrading to latest melpa release should fix the issue.

To be read "latest dash release".

**Comment by fgabolde** [comment]
I am running dash 20190221.1029 from MELPA (and dash-functional 20180107.1618 also from MELPA) and I have the same issue.

**Comment by yyoncho** [comment]
@fgabolde - can you remove all elc files in your .emacs.d directory and retry.  e. g. `find -name "*elc" | xargs rm`

**Comment by fgabolde** [comment]
@yyoncho that was it, of course. Sorry for the noise.
