### ISSUE TITLE
dap-java-run-test-method, dap-java-run-test-class don't seem to identify maven failsafe tests

### ISSUE THREAD

**Issue by david-oc-miller** [yyoncho/dap-mode#17]
Hi @yyoncho, lsp-java and dap-mode are the best.

On regular surefire tests (test class ending in Test.java), the dap-java test methods seem to find and run the test methods OK.

On failsafe integration tests (test class ending in IT.java), it doesn't find any tests:

> Test run finished after 45 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

Even though the integration tests have the same @Test annotations as the regular tests.

The IT tests do have `@RunWith(SpringJUnit4ClassRunner.class)` and `@ContextConfiguration` annotations though.

Am I missing something?

**Comment by yyoncho** [comment]
`dap-mode` is using jdt-che(https://github.com/eclipse/che-ls-jdt ) to fetch the class name and then pass it to JUnit runner (https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher). Can you set `lsp-print-io` and `dap-print-io` to t and inspect:
1. Do jdt-che resolve the proper classname?
2. Do the runner successfully executes the test?

Alternatively, If you can post standalone project or test which I can use to reproduce the issue.

**Comment by david-oc-miller** [comment]
Attached is a zip file with a test project.  `mvn clean install` runs one unit test (SurefireTest.java) and one integration test (FailsafeIT.java).  `maven-test-file` from FailsafeIT.java will run the test case.

[failsafe-test.zip](https://github.com/yyoncho/dap-mode/files/2587529/failsafe-test.zip)

Starting just now, `dap-java-run-test-class` gives me an exception, `WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: tech.davidocmiller.FailsafeIT`.


But, since Maven does run it, it would be great if dap-mode could run it too.

**Comment by david-oc-miller** [comment]
Attached here is the \*messages\* buffer output after setting lsp-print-io and dap-print-io, and trying to run the test.  From line 929, it seems like jdt-che did resolve the proper classname.   At line 968 is what looks like the right classpath.  Then I don't see any output after that.  It just doesn't find any test methods:

> 
Test run finished after 26 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

\*lsp-java stderr\* buffer is empty.

[failsafe-it-messages-buffer.txt](https://github.com/yyoncho/dap-mode/files/2587544/failsafe-it-messages-buffer.txt)

**Comment by yyoncho** [comment]
It seems like the issue is with the console runner not picking up the test only because it is ending with IT not Test. I have tried it with latest console launcher (1.3.1) and it fails too.

Quoting JUnit guys to comment: @marcphilipp @sormuras , is this by desing or is there a way to force running tests ending with IT?  


> java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=33000 -jar /home/kyoncho/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c tech.davidocmiller.FailSafeIT

> java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=33000 -jar /home/kyoncho/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c tech.davidocmiller.FailsafeTest

**Comment by sormuras** [comment]
iirc, there was/is a feature request to let `-c, --select-class=CLASS` override the `-n` pattern. Can't find it in our issue tracker, though.

**Comment by sormuras** [comment]
Found it: https://github.com/junit-team/junit5/issues/733

**Comment by yyoncho** [comment]
@sormuras Thanks!

@david-oc-miller 
You could use ...
``` emacs-lisp
(setq dap-java-test-additional-args '("-n" "\".*(Test|IT).*\""))
```
... extend the default one from https://github.com/yyoncho/dap-mode/issues/17#issuecomment-439301702

**Comment by david-oc-miller** [comment]
`dap-java-test-additional-args` works, thanks much.
