### ISSUE TITLE
dap-python setup not working

### ISSUE THREAD

**Issue by RenWenshan** [yyoncho/dap-mode#19]
Run `M-x dap-debug` against a python file raises:

```
python -m ptvsd --port 32000 /home/rws/hack/test.py
usage: python -m ptvsd [-h] [--nodebug] [--client] --host HOST --port PORT [--multiprocess] [-m MODULE] [-c CODE] [--pid PID]
                       [--single-session] [--wait] [-V]
                       [filename]
python -m ptvsd: error: argument --host is required
```

while host should have been specified at https://github.com/yyoncho/dap-mode/blob/2cf98d4a2268fa4ca92a35723ed3883eff734d1f/dap-python.el#L52

I setup dap following the official README:

```
(require 'dap-mode)
(require 'dap-ui)
(dap-mode 1)
(dap-ui-mode 1)
(require 'dap-python)
```

(emacs-version) => "GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2018-10-22"

**Comment by yyoncho** [comment]
ptvsd 4.2 have introduced the new mandatory flag.

> sudo pip uninstall ptvsd
> sudo pip install "ptvsd==4.1.1a11"

Should fix the issue. I will update the readme.

**Comment by yyoncho** [comment]
Heads up that dap-mode is now changed to use ptvsd 4.2 .
