### ISSUE TITLE
Debugging java test method leads to `Debugger failed to attach`

### ISSUE THREAD

**Issue by iocanel** [yyoncho/dap-mode#37]
While debugging main class seems to work fine, when I try to debug a test class or method, I get this:

    Listening for transport dt_socket at address: 33000
    Debugger failed to attach: handshake failed - connection prematurally closed.

**Comment by yyoncho** [comment]
> Debugger failed to attach: handshake failed - connection prematurally closed.

Here it is how debugging works:

1. Test is started with remote debugging set to listen on port 30000
2. dap-mode starts a loop which waits for port to be taken.
3. when the port is taken, dap-mode starts the debug adapter with launch type = `attach` 

The error message is coming from the test connection happening at 2). 

Did you try to run the test without debug? Are these the only messages in the output log? Can you try to do `lsp-java-build-project` before starting the test?

**Comment by iocanel** [comment]
**Note**: The error message will appear upon timeout, **or** upon any interaction with the editor _(key press or mouse click)_.

**Comment by iocanel** [comment]
Upon further investigation, I come the conclusion that this error message is misleading, as I managed to succesfully debug a test, even though the message appears (I can't get rid of it).

**Comment by yyoncho** [comment]
I was unable to find a way to test whether particular port is taken so I am opening a testing connection to the debugged process and then I am closing it - thus this error message. I am closing the bug based on the previous comment.
