### ISSUE TITLE
not able to debug java project

### ISSUE THREAD

**Issue by Hans-Maulwurf** [yyoncho/dap-mode#4]
hey guys,

i'm very impressed what's possible with lsp and dap-mode. Looking forward to use is, i tried to configure everything and when trying to debug my maven/java project, i only get this

`lsp-send-execute-command: Capability not supported by the language server: "executeCommandProvider"`

No matter if i use "dap-debug" oder "dap-java-debug" the result is the same. Am I using the wrong version of the language server? (used the linux-snippets in the README)

thank you for your help

**Comment by yyoncho** [comment]
Can you set `lsp-print-io` to t and `dap-print-io` to t and paste the output? I want to know which command has this output.

**Comment by Hans-Maulwurf** [comment]
in this case i used dap-java-debug

`Building workspace - 83%
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "004a80a8-741c-4be8-8bb2-7780ac5d382c",
    "task": "Building workspace",
    "subTask": "",
    "status": "Building workspace - 100%",
    "totalWork": 1000,
    "workDone": 1000,
    "complete": true
  }
}
Building workspace - 100% (done)
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "004a80a8-741c-4be8-8bb2-7780ac5d382c",
    "task": "Building workspace",
    "subTask": "",
    "status": "Building workspace - 100%",
    "totalWork": 1000,
    "workDone": 1000,
    "complete": true
  }
}
Building workspace - 100% (done)
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "8764d843-bcdf-43af-92e7-6c4f3dd7bc58",
    "task": "Building workspace",
    "status": "Building workspace - 0%",
    "totalWork": 1000,
    "workDone": 0,
    "complete": false
  }
}
Building workspace - 0%
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "8764d843-bcdf-43af-92e7-6c4f3dd7bc58",
    "task": "Building workspace",
    "subTask": "",
    "status": "Building workspace - 34%",
    "totalWork": 1000,
    "workDone": 339,
    "complete": false
  }
}
Building workspace - 34%
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "8764d843-bcdf-43af-92e7-6c4f3dd7bc58",
    "task": "Building workspace",
    "subTask": "",
    "status": "Building workspace - 100%",
    "totalWork": 1000,
    "workDone": 1000,
    "complete": true
  }
}
Building workspace - 100% (done)
Output from language server: {
  "jsonrpc": "2.0",
  "method": "language/progressReport",
  "params": {
    "id": "8764d843-bcdf-43af-92e7-6c4f3dd7bc58",
    "task": "Building workspace",
    "subTask": "",
    "status": "Building workspace - 100%",
    "totalWork": 1000,
    "workDone": 1000,
    "complete": true
  }
}
Building workspace - 100% (done)
lsp-send-execute-command: Capability not supported by the language server: "executeCommandProvider"`

**Comment by yyoncho** [comment]
Nevermind, I managed to find which was causing this issue - https://github.com/emacs-lsp/lsp-mode/commit/8b0648062c1f2a5784a331880fa85ceac20cc97f .


You can temporarily fix the issue until the proper fix is found by commenting those lines.

**Comment by yyoncho** [comment]
To be more specific, you should execute the following in your system:

``` elisp
(defun lsp--send-execute-command (command &optional args)
  "Create and send a 'workspace/executeCommand' message having
command COMMAND and optionsl ARGS"
  (lsp--cur-workspace-check)
  ;; (unless (lsp--capability "executeCommandProvider")
  ;;   (signal 'lsp-capability-not-supported (list "executeCommandProvider")))
  (lsp--send-request
   (lsp--make-request
    "workspace/executeCommand"
    (lsp--make-execute-command-params command args))))
```

**Comment by yyoncho** [comment]
I have filed https://github.com/eclipse/eclipse.jdt.ls/issues/757 to track the root cause.

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-java/commit/6e53118efdf7c4e4055d363ad1b87859768d72a9
