### ISSUE TITLE
Trouble setting up PHP debugging 

### ISSUE THREAD

**Issue by gjm** [yyoncho/dap-mode#42]
Hi.

I'm trying to setup PHP debugging. I've installed the  `felixbecker/vscode-php-debug` extension and it seems to be working fine (runs on command line with no errors).

When I run `M-x dap-debug` on emacs i get: 

```
Symbol’s function definition is void: first
```
Is there something I'm doing wrong or missing some step? How can I help debug this isse?

Here's a stack trace of the execution:
```
Debugger entered--Lisp error: (void-function first)
  first(("Php Run Configuration" :type "node" :cwd nil :request "launch" :name "Php Debug" :args ("--server=4711") :sourceMaps t))
  #[257 "\300!B\207" [first] 3 "\n\n(fn IT)"](("Php Run Configuration" :type "node" :cwd nil :request "launch" :name "Php Debug" :args ("--server=4711") :sourceMaps t))
  mapcar(#[257 "\300!B\207" [first] 3 "\n\n(fn IT)"] (("Php Run Configuration" :type "node" :cwd nil :request "launch" :name "Php Debug" :args ("--server=4711") :sourceMaps t)))
  dap--completing-read("Select configuration template: " (("Php Run Configuration" :type "node" :cwd nil :request "launch" :name "Php Debug" :args ("--server=4711") :sourceMaps t)) first nil t)
  byte-code("\301\302\303\304\305\306%A!C\207" [dap--debug-template-configurations copy-tree dap--completing-read "Select configuration template: " first nil t] 7)
  #<subr call-interactively>(dap-debug record nil)
  apply(#<subr call-interactively> dap-debug (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> dap-debug record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (dap-debug record nil))
  call-interactively(dap-debug record nil)
  #[1025 "\306\211?\205
```

**Comment by yyoncho** [comment]
Can you eval (require 'cl-lib)  which apparently is missing from dap-mode?

**Comment by gjm** [comment]
I've tried it with no result...

Here's my init snippet. Maybe I'm doing something wrong?

(use-package dap-mode
  :ensure t
  :after lsp-mode
  :init
  (require 'cl-lib)
  :config
  (require 'dap-php))


Atentamente,

Gonçalo Marrafa

**Comment by yyoncho** [comment]
Which emacs version do you use?

**Comment by gjm** [comment]
I'm using 25.2 on Ubuntu 18.10.

Atentamente,

Gonçalo Marrafa

**Comment by yyoncho** [comment]
From what I can see `first` is available in 25.2:

```
(require 'cl)
(require 'cl-lib) 
(first '(1 2 3))
```
This must return 1.

**Comment by gjm** [comment]
OK, so I added the (require 'cl) to my init setup and now what happens is,
when i M-x dap-debug, I'm prompted to choose the runtime config. I choose
"Php Run Configuration" and then I get: dap-debug: There is no debug
provider for language node

**Comment by yyoncho** [comment]
This one is bug in dap-php 

```
(dap-register-debug-provider "php" 'dap-php--populate-start-file-args)
(dap-register-debug-template "Php Run Configuration"
                             (list :type "php"
                                   :cwd nil
                                   :request "launch"
                                   :name "Php Debug"
                                   :args '("--server=4711")
                                   :sourceMaps t))
```
should solve that issue.

**Comment by gjm** [comment]
Should I use this instead of (require 'dap-php) ?


Gonçalo Marrafa

**Comment by yyoncho** [comment]
This is the correct script:
```
(defun dap-php--populate-start-file-args (conf)
  "Populate CONF with the required arguments."
  (-> conf
      (dap--put-if-absent :dap-server-path dap-php-debug-program)
      (dap--put-if-absent :type "php")
      (dap--put-if-absent :cwd (lsp-find-session-folder (lsp-session) (buffer-file-name)))
      (dap--put-if-absent :name "Php Debug")))

(dap-register-debug-provider "php" 'dap-php--populate-start-file-args)
(dap-register-debug-template "Php Run Configuration"
                             (list :type "php"
                                   :cwd nil
                                   :request "launch"
                                   :name "Php Debug"
                                   :args '("--server=4711")
                                   :sourceMaps t
                                   ))
```

**Comment by yyoncho** [comment]
> Should I use this instead of (require 'dap-php) ?

Yes. Just for the record, these two bugs https://github.com/yyoncho/dap-mode/issues/35 https://github.com/yyoncho/dap-mode/issues/36 are related to PHP adapter, I am still waiting for logs for them.

**Comment by yyoncho** [comment]
You should test this variant too - it should be either php everywhere or node.

```
(defun dap-php--populate-start-file-args (conf)
  "Populate CONF with the required arguments."
  (-> conf
      (dap--put-if-absent :dap-server-path dap-php-debug-program)
      (dap--put-if-absent :type "node")
      (dap--put-if-absent :cwd (lsp-find-session-folder (lsp-session) (buffer-file-name)))
      (dap--put-if-absent :name "Php Debug")))

(dap-register-debug-provider "node" 'dap-php--populate-start-file-args)
(dap-register-debug-template "Php Run Configuration"
                             (list :type "node"
                                   :cwd nil
                                   :request "launch"
                                   :name "Php Debug"
                                   :args '("--server=4711")
                                   :sourceMaps t
                                   ))
```

**Comment by gjm** [comment]
OK, so I can start the debugger with this configuration. I to add

(defcustom dap-php-debug-program `("node" ,(expand-file-name
"~/.extensions/php/out/phpDebug.js"))
    "The path to the php debugger."
    :group 'dap-php
    :type '(repeat string))

to get it to start OK. AFAIK the debug server is running on port 9000 (I
can confirm with netstat and ps). If I try a request on the browser it
seems to connect to the server because it blocks but nothing happens on
emacs side...

Is there some way to check the connection is really being established?

BTW, the config has the arg --server=4711 but the server binds to port 9000
which is the default Xdebug port. Is there something wrong here?

Thanks for all your help and patience so far!

Gonçalo Marrafa

**Comment by yyoncho** [comment]
You may do dap-ui-sessions which will list the debug sessions that are started and the blocked threads. 

> Is there some way to check the connection is really being established?

You may monitor \*Messages\* buffer for client server communications (it is self describing pretty much).

About the port - the best settings should be provided by debug adapter users.

**Comment by yyoncho** [comment]
CC @tomterl the author of the PHP integration.

**Comment by tomterl** [comment]
On the emacs side nothing happens automatically -- you have to manually select the thread and `step in`  - I use the pre-defined hydra: `M-x dap-hydra RET st RET i`;

**Comment by yyoncho** [comment]
@tomterl 

> On the emacs side nothing happens automatically

I am assuming that session list will work too, right? I tried to make the debugger non-intrusive. E. g. if you have multiple breakpoints hit in different threads it will be inconvenient if it steals your focus.

**Comment by yyoncho** [comment]
Speaking of this, it seems like if there is some kind of indication in the modeline about the number of active debug session, the number of stopped threads and so on.

**Comment by tomterl** [comment]
Thread selection looks like this:
![image](https://user-images.githubusercontent.com/494717/52658143-a23b2e80-2efa-11e9-8dcf-018458e17b99.png)

**Comment by tomterl** [comment]
> @tomterl
> 
> > On the emacs side nothing happens automatically
> 
> I am assuming that session list will work too, right? I tried to make the debugger non-intrusive. E. g. if you have multiple breakpoints hit in different threads it will be inconvenient if it steals your focus.

Yes, wrt/ the issue #36 session-ui works and is usable.

**Comment by tomterl** [comment]
I quickly generated a PR with my working `dap-php` to avoid hickups so early in the adoption phase

**Comment by tomterl** [comment]
@gjm please don't hesitate to ask further questions, IMHO a working php-infrastructure in emacs is paramount

**Comment by gjm** [comment]
I seem to have the debuuger working... but I can't really figure out the
workflow...

I can see the incoming requests, I can step in on a request but, when i
create a breakpoint somewhere and choose "continue" I expect it to break at
that point but it doesn't... Can someone point me to some sort of
documentation/guide on how to use the debugger? The basics at least?

PS: now I use Geben for PHP debugging but dap seems to have great potential.

Gonçalo Marrafa

**Comment by tomterl** [comment]
wrt/ breakpoints: Sometimes breakpoints don't trigger - but that's a problem I had with geben, too; sometimes breaking a line above/below did the trick; or maybe you encounter #35?

**Comment by yyoncho** [comment]
@tomterl  there are a lot of bugs related to the breakpoints in the php debug adapter repo - https://github.com/felixfbecker/vscode-php-debug/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+breakpoint

**Comment by tomterl** [comment]
> @tomterl there are a lot of bugs related to the breakpoints in the php debug adapter repo - https://github.com/felixfbecker/vscode-php-debug/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+breakpoint

yeah, that list looks kind of scary - but a lot of those are user-errors (skimping through a couple of them); will have a deeper look (again) when my workload allows it (next month maybe)

**Comment by tomterl** [comment]
Nevertheless: @gjm This issue could be closed, right? The basic setup isn't the problem anymore?

**Comment by yyoncho** [comment]
Closing based on the previos comment.
