### ISSUE TITLE
Is there a way of showing the result of debug on the compilation buffer??

### ISSUE THREAD

**Issue by blutics** [yyoncho/dap-mode#5]
or is there a way to make it showing results on the same buffer not with making a new buffer every time running dap-debug?

**Comment by yyoncho** [comment]
I am on a vacation 4 days, I will provide a flag when I am back. If you want to temporary fix this you might patch line
`(output-buffer (generate-new-buffer "*out*"))` to reuse the buffer.

**Comment by yyoncho** [comment]
Now you can call `dap-debug`  and select `Java Run Configuration (compile/attach)` . This will start the java application into *compilation* buffer and it will attach to it.
